version: '2.2'
services:
  nginx:
    build:
      context: ../docker-compose
      dockerfile: nginx/nginx.dockerfile
    container_name: nginx_$APP_NAME
    ports:
      - "8080:8080"
    volumes:
      - ../:/var/www/html/$APP_NAME
    depends_on:
      - php
      - redis
    networks:
      - laravel
  php:
    build:
      context: ../docker-compose
      dockerfile: php/php.dockerfile
    container_name: php_$APP_NAME
    ports:
      - "9000:9000"
    volumes:
      - ../:/var/www/html/$APP_NAME
      - ./php/local.ini:/etc/php/conf.d/local.ini
    networks:
      - laravel
  redis:
    build:
      context: ../docker-compose
      dockerfile: redis/redis.dockerfile
    restart: always
    container_name: redis_$APP_NAME
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass secret
    volumes:
      - ../docker-compose/redis/data:/data
    networks:
      - laravel
  composer:
    build:
      context: ../docker-compose
      dockerfile: composer/composer.dockerfile
    container_name: composer_$APP_NAME
    volumes:
      - ../:/var/www/html/$APP_NAME
    working_dir: /var/www/html/$APP_NAME
    networks:
      - laravel
  artisan:
    build:
      context: ../docker-compose
      dockerfile: php/php.dockerfile
    container_name: artisan_$APP_NAME
    volumes:
      - ../:/var/www/html/code
    entrypoint: [ "php", "/var/www/html/code/$APP_NAME/artisan" ]
    networks:
      - laravel
volumes:
  redis:
    driver: local
networks:
  laravel:
    driver: bridge
