version: '2.2'
services:
  nginx:
    build:
      context: ../docker-compose
      dockerfile: nginx/nginx.dockerfile
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./code/:/var/www/html/code
    depends_on:
      - php
      - redis
    networks:
      - laravel
  php:
    build:
      context: ../docker-compose
      dockerfile: php/php.dockerfile
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./code/:/var/www/html/code
      - ./php/local.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel
  redis:
    build:
      context: ../docker-compose
      dockerfile: redis/redis.dockerfile
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass secret
    volumes:
      - ./redis/data:/data
    networks:
      - laravel
  composer:
    build:
      context: ../docker-compose
      dockerfile: composer/composer.dockerfile
    container_name: composer
    volumes:
      - ./code:/var/www/html/code
    working_dir: /var/www/html/code/$APP_NAME
    networks:
      - laravel
  artisan:
    build:
      context: ../docker-compose
      dockerfile: php/php.dockerfile
    container_name: artisan
    volumes:
      - ./code/:/var/www/html/code
    entrypoint: [ "php", "/var/www/html/code/$APP_NAME/artisan" ]
    networks:
      - laravel
volumes:
  redis:
    driver: local
networks:
  laravel:
    driver: bridge
